# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

# Try out "interactive-mode"
os: Windows Server 2012 R2

# build version format
version: "{build}"

# Set a known clone folder
clone_folder: c:\projects\nodegit

# fix lineendings in Windows
init:
  - git config --global core.autocrlf input
  - git config --global user.name "wy"
  - git config --global user.email wy@tr.com

# what combinations to test
environment:
  JOBS: 4
  BUILD_ONLY: true
  GIT_SSH: c:\projects\nodegit\vendor\plink.exe
  GYP_MSVS_VERSION: 2013
  matrix:
    # Node.js
    - nodejs_version: "5.0"

matrix:
  fast_finish: true

# Get the latest stable version of Node 0.STABLE.latest
install:
  - ps: Install-Product node $env:nodejs_version
  - ps: Start-Process c:\projects\nodegit\vendor\pageant.exe c:\projects\nodegit\vendor\private.ppk
  - cmd: npm install -g node-gyp
  - npm install

test_script:
  - node --version
  - npm --version
  - cmd: npm test

on_success:
  - IF %APPVEYOR_REPO_TAG%==true npm install -g node-pre-gyp
  - IF %APPVEYOR_REPO_TAG%==true npm install -g aws-sdk
  - IF %APPVEYOR_REPO_TAG%==true node-pre-gyp package
  - IF %APPVEYOR_REPO_TAG%==true node-pre-gyp publish

build: off
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'nodegit-Release'
  provider: GitHub
  auth_token:
    secure: e1557d74ab83b7df5ad5d41c6403d8c2ba656782 # your encrypted token from GitHub
  artifact: build/*            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only
    
branches:
  only:
    - master
    - v0.3
