#!/usr/bin/env node
var cp = require("child_process");
var path = require("path");
var child = cp.spawn("npm", ["install", "--ignore-scripts"]);
child.stderr.pipe(process.stderr);
child.stdout.pipe(process.stdout);
child.on("exit", function(code) {
  if (code != 0) {
    process.exit(code);
  }

  var downloadVendorDependency = require("./helpers/downloadVendorDependency");
  var Promise = Promise || require("nodegit-promise");

  return downloadVendorDependency("http_parser")
    .then(function() {
      return downloadVendorDependency("libgit2");
    })
    .then(function() {
      if (process.platform == "win32") {
        return;
      }

      return downloadVendorDependency("libssh2")
        .then(function(vendorPath) {
          if (vendorPath) {
            return new Promise(function(resolve, reject) {
              cp.execFile(
                path.join(vendorPath, "configure"),
                {cwd: vendorPath},
                function(err, stdout, stderr) {
                  if (err) {
                    console.error(err);
                    console.error(stderr);
                    reject(err, stderr);
                  }
                  else {
                    resolve(stdout);
                  }
                }
              );
            });
          }
        });
    })
    .catch(function(reason) {
      console.error(reason);
    });
});
