#!/usr/bin/env node
var Promise = Promise || require("nodegit-promise");
var generate = require("../generate");
var npg = require("./helpers/nodePreGyp");

generate()
  .then(function() {
    var force = ~process.argv.indexOf("-f") || ~process.argv.indexOf("--force");
    var cmd = force ? "rebuild": "build";
    var args = [cmd].concat(process.argv.slice(2));

    return npg(args);
  });
